my_site/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
# 下面两个包是为了配置media
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('go-admin/', admin.site.urls),
    path('', include('post.urls', namespace='home')),
    path('post/', include('post.urls', namespace='post')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/my_site/post/urls.py
from django.urls import path
from . import views


app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='home'),
    path('post-list/', views.post_list, name='post_list'),
    path('post-update/<int:id>/', views.post_update, name='post_update'),
    path('post-create/', views.post_create, name='post_create'),
    path('post-detail/<int:id>/', views.post_detail, name='post_detail'),
    
]

my_site/my_site/post/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='author'
        )
    title = models.CharField(max_length=100)
    body = models.TextField(blank=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    views = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank=True)
    is_public = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        pass

my_site/my_site/post/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'body',
            'is_public',
            'tags',
        )

my_site/my_site/post/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import PostCreateForm
from django.contrib.auth.models import User
import markdown
# Create your views here.


def post_list(request):
    if request.user.is_superuser:
        posts = Post.objects.all()
    else:
        posts = Post.objects.filter(is_public=True)
    context = {
        'posts': posts,
    }
    return render(request, 'post/list.html', context=context)


def post_detail(request, id):
    post = Post.objects.get(id=id)
    if post.is_public:
        post.views += 1
        post.save(update_fields=['views'])
        post.body = markdown.markdown(post.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            ])
        context = {
            'post': post,
        }
        return render(request, 'post/detail.html', context=context)
    else:
        if request.user.is_superuser:
            context = {
                'post': post,
            }
            return render(request, 'post/detail.html', context=context)
        else:
            return redirect('post:post_list')


@login_required(login_url='userprofile:login')
def post_create(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            post_create_form = PostCreateForm(data=request.POST)
            if post_create_form.is_valid():
                new_post = post_create_form.save(commit=False)
                new_post.user = User.objects.get(id=request.user.id)
                new_post.save()
                post_create_form.save_m2m()  # tags保存方法
                return redirect("post:post_list")
            else:
                return HttpResponse("<script>alert('输入不合规');</script>")
        elif request.method == 'GET':
            return render(request, 'post/create.html')
        else:
            return HttpResponse('<script>please use POST or GET method</script>')
    else:
        return redirect('post:post_list')


@login_required(login_url='userprofile:login')
def post_update(request, id):
    post = Post.objects.get(id=id)
    if request.user.is_superuser:
        if request.method == 'POST':
            post_create_form = PostCreateForm(data=request.POST)
            if post_create_form.is_valid():
                post_data = post_create_form.cleaned_data  # 不清洗数据，在获取 is_public 时会报错，可能是 radio 控件在未勾选提交表单时不会提交数据，导致KeyError错误
                post.title = post_data['title']
                post.body = post_data['body']
                post.is_public = post_data['is_public']
                # post.tags = request.POST['tags']
                post.save()
                # post_create_form.save_m2m()
                return redirect('post:post_detail', id=id)
            else:
                return HttpResponse('input  content error')
        elif request.method == 'GET':
            context = {
                'post': post,
            }
            return render(request, 'post/update.html', context=context)
        else:
            return HttpResponse("<script>please use POST or GET method</script>")
    else:
        return redirect('post:post_list')


def post_delete(request, id):
    pass

my_site/my_site/templates/post/create.html
{% extends "base.html" %}

{% block head %}
<title>{{create}}</title>
{% endblock head %}

{% block content %}
<div class="content" style="margin:20px">
<form action="." method="POST">
    {% csrf_token %}
    <div class="field">
        <label class="label">Title</label>
        <div class="control">
            <input class="input" type="text" placeholder="Title input" name="title">
        </div>
    </div>

    <div class="field">
        <label class="label">Message</label>
        <div class="control">
            <textarea class="textarea" placeholder="Body" name="body" rows="18"></textarea>
        </div>
    </div>

    <div class="field">
        <label class="label">tags</label>
        <div class="control">
            <input class="input" type="text" placeholder="tags input(english ,)" name="tags">
        </div>
    </div>

    <div class="field">
        <div class="control">
            <label class="checkbox">
                <input type="checkbox" name="is_public">
                show this post to everyone?
            </label>
        </div>
    </div>

    <div class="field is-grouped">
        <div class="control">
            <button class="button is-link" type="submit">Submit</button>
        </div>
    </div>
</form>
</div>
{% endblock content %}

my_site/my_site/templates/post/detail.html
{% extends "base.html" %}
{% load static %}

{% block head %}

<title>{{ post.title }}</title>

{% endblock head %}


{% block content %}

<div class="content" style='margin:20px'>
<h1>{{ post.title }}</h1><sup class="has-text-grey-lighter">{{ post.created|date:'Y-m-d'}}&nbsp;<i class="fa fa-eye"></i>&nbsp;{{post.views}}
{% if user.is_superuser %}
<a href="{% url 'post:post_update' post.id %}">修改</a>
{% endif %}
</sup>
<p>{{ post.body|safe }}</p>
</div>




{% endblock content %}

my_site/my_site/templates/post/list.html
{% extends "base.html" %}

{% block head %}

<title>wongxy</title>
{% endblock head %}


{% block content %}

<div class="content" style="margin:20px">
    {% for post in posts %}
        <div class="columns is-mobile">
            <div class="column">
                <a href="{% url 'post:post_detail' post.id %}">
                    <h4 title="{{ post.body|slice:'60' }}">
                        {{ post.title }}
                        <span class="has-text-grey-lighter is-size-7">&nbsp;&nbsp;{{ post.created|date:'Y-m-d' }}</span>
                    </h4>
                </a>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock content %}

my_site/my_site/templates/post/update.html
{% extends "base.html" %}

{% block head %}
<title>create</title>
{% endblock head %}

{% block content %}
<div class="content" style="margin:20px">
<form action="." method="POST">
    {% csrf_token %}
    <div class="field">
        <label class="label">Title</label>
        <div class="control">
            <input class="input" type="text" placeholder="Title input" name="title" value="{{post.title}}">
        </div>
    </div>

    <div class="field">
        <label class="label">Message</label>
        <div class="control">
            <textarea class="textarea" placeholder="Body" name="body" rows="18">{{post.body}}</textarea>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <label class="checkbox">
                <input type="checkbox" name="is_public"
                {% if post.is_public %}
                checked
                {% endif %}
                >
                show this post to everyone?
            </label>
        </div>
    </div>

    <div class="field is-grouped">
        <div class="control">
            <button class="button is-link" type="submit">Submit</button>
        </div>
    </div>
</form>
</div>
{% endblock content %}