my_site/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
# 下面两个包是为了配置media
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('go-admin/', admin.site.urls),
    path('', include('post.urls', namespace='home')),
    path('post/', include('post.urls', namespace='post')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/my_site/post/urls.py
from django.urls import path
from . import views


app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='home'),
    path('post-list/', views.post_list, name='post_list'),
    path('post-update/<int:id>/', views.post_update, name='post_update'),
    path('post-create/', views.post_create, name='post_create'),
    path('post-detail/<int:id>/', views.post_detail, name='post_detail'),
    
]

my_site/my_site/userprofile/urls.py
from django.urls import path
from . import views


app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('profile-edit/', views.profile_edit, name='profile_edit'),

]

my_site/my_site/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% comment %} -------------------------------------------- {% endcomment %}
    {% block head %}
    {% endblock head %}
    <link href="https://q2.qlogo.cn/headimg_dl?dst_uin=286183317&spec=100" rel="SHORTCUT ICON">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" href="{% static 'md_css/colorful.css' %}">
</head>

<body>
    <div class="container">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="http://116.62.167.164">
                    <!-- 头像 -->
                    <img class="is-rounded" src="{% if user.is_superuser %} https://q2.qlogo.cn/headimg_dl?dst_uin=286183317&spec=100
                    {% elif user.profile.avatar %}
                    {{user.profile.avatar.url}}
                    {%else%}https://q2.qlogo.cn/headimg_dl?dst_uin=286183317&spec=100{%endif%}">

                </a>

                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                    data-target="navbar">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbar" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="http://116.62.167.164">
                        HOME
                    </a>
                    <a class="navbar-item">
                        TOOLS
                    </a>

                    <a class="navbar-item">
                        ABOUT
                    </a>

                    {% if user.is_authenticated %}
                    <a class="navbar-item" href="{% url 'userprofile:profile_edit' %}">
                        {{user.username}}
                    </a>
                    {% endif %}

                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            {% comment %} ------------------------------ {% endcomment %}
                            {% if not user.is_authenticated %}
                            <a class="button is-primary is-outlined" href="{% url 'userprofile:login' %}">
                                登录
                            </a>
                            <a class="button" href="{% url 'userprofile:register' %}">
                                注册
                            </a>
                            {% else %}
                            {% if user.is_superuser %}
                            <a class="button is-success" href="{% url 'post:post_create' %}">
                                写点？
                            </a>
                            {% endif %}
                            <a class="button" title="{{user.username}}退出登录" href="{% url 'userprofile:logout' %}">
                                <i class="fa fa-power-off"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
    </div>
    </nav>
    {% comment %} ----------------------------------------- {% endcomment %}
    {% block content %}
    {% endblock content %}

    <footer class="footer" style="height: 20px">
        <div class="content has-text-centered">
            <p class="is-italic">
                A man is not old as long as he is seeking something. A man is not old until regrets take the place
                of dreams.
            </p>
        </div>
    </footer>
    </div>

    <script>
        // 导航栏相关
        document.addEventListener('DOMContentLoaded', () => {

            // Get all "navbar-burger" elements
            const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

            // Check if there are any navbar burgers
            if ($navbarBurgers.length > 0) {

                // Add a click event on each of them
                $navbarBurgers.forEach(el => {
                    el.addEventListener('click', () => {

                        // Get the target from the "data-target" attribute
                        const target = el.dataset.target;
                        const $target = document.getElementById(target);

                        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                        el.classList.toggle('is-active');
                        $target.classList.toggle('is-active');

                    });
                });
            }

        });
    </script>
</body>

</html>